fix: try fail

diff --git a/.github/workflows/caller.yml b/.github/workflows/caller.yml
--- a/.github/workflows/caller.yml
+++ b/.github/workflows/caller.yml
@@ -10,9 +10,37 @@ jobs:
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     uses: ChJL/workflow-test/.github/workflows/git_tag.yml@main
 
-  update-version:
-    name: Update version
-    needs: create-new-tag
+#   update-version:
+#     name: Update version
+#     needs: create-new-tag
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Set up Python 3.7
+#         uses: actions/setup-python@v1
+#         with:
+#           python-version: '3.7'
+
+#       - uses: actions/checkout@v2
+#         with:
+#           ref: ${{ github.head_ref }}
+
+#       - name: toml-cli
+#         run: |
+#           pip install toml-cli
+#           toml get --toml-path pyproject.toml tool.poetry.name
+#           toml set --toml-path pyproject.toml tool.poetry.version ${{ needs.create-new-tag.outputs.new_version}}
+
+#       - uses: stefanzweifel/git-auto-commit-action@v4
+#         with:
+#           commit_message: Update pyproject version
+#       - uses: ncipollo/release-action@v1
+#         with:
+#           tag: ${{ needs.create-new-tag.outputs.new_version }}
+#           name: Release ${{ needs.create-new-tag.outputs.new_version }}
+
+  simulate-push-to-ecr:
+    needs:
+      - create-new-tag
     runs-on: ubuntu-latest
     steps:
       - name: Set up Python 3.7
@@ -33,19 +61,15 @@ jobs:
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: Update pyproject version
+          
+      - name: Simulate succeess or failure
+        run: |
+          echo "ecr fail!"
+          exit 1
       - uses: ncipollo/release-action@v1
         with:
           tag: ${{ needs.create-new-tag.outputs.new_version }}
           name: Release ${{ needs.create-new-tag.outputs.new_version }}
-
-  simulate-push-to-ecr:
-    needs:
-      - update-version
-    runs-on: ubuntu-latest
-    steps:
-      - name: Simulate succeess or failure
-        run: |
-          echo "ecr success!"
 
   # This section can be used when you want to delete the tag
   # Remember to set the condition (e.g. if: )
@@ -64,28 +88,28 @@ jobs:
         run: |
           git push --delete origin ${{needs.create-new-tag.outputs.new_tag}}
 
-  re-update-pyproject:
-    needs:
-      - delete-tag
-      - create-new-tag
-    if: "always() && (needs.delete-tag.result == 'success')"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v1
-        with:
-          python-version: '3.7'
+#   re-update-pyproject:
+#     needs:
+#       - delete-tag
+#       - create-new-tag
+#     if: "always() && (needs.delete-tag.result == 'success')"
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Set up Python 3.7
+#         uses: actions/setup-python@v1
+#         with:
+#           python-version: '3.7'
 
-      - uses: actions/checkout@v2
-        with:
-          ref: ${{ github.head_ref }}
+#       - uses: actions/checkout@v2
+#         with:
+#           ref: ${{ github.head_ref }}
 
-      - name: toml-cli
-        run: |
-          pip install toml-cli
-          toml get --toml-path pyproject.toml tool.poetry.name
-          toml set --toml-path pyproject.toml tool.poetry.version ${{ needs.create-new-tag.outputs.previous_version}}
+#       - name: toml-cli
+#         run: |
+#           pip install toml-cli
+#           toml get --toml-path pyproject.toml tool.poetry.name
+#           toml set --toml-path pyproject.toml tool.poetry.version ${{ needs.create-new-tag.outputs.previous_version}}
 
-      - uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          commit_message: Reverse pyproject version
+#       - uses: stefanzweifel/git-auto-commit-action@v4
+#         with:
+#           commit_message: Reverse pyproject version
